### ISSUE TITLE
회원가입 수정: 생년월일 이슈

### ISSUE THREAD

**Issue by Senna97** [likelion-backend-2nd-project-team11/book-more#193]
### 내용
- 회원가입시에 생년월일 형식이 맞음에도 불구하고 형식이 올바르지 않다고 하는 경우가 발생합니다.
- 지금과 같은 입력이 아닌 셀렉트 박스로 변경하여 주세요.

**Comment by menuhwang** [comment]
프로필 사진 수정 모달 분리 커밋과 충돌이 예상되어 머지 후 작업하겠습니다.
